package hello.repository;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.CrossOrigin;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;


@CrossOrigin(origins = "http://localhost:4200")
@Controller    // This means that this class is a Controller

@RequestMapping(path="/demo") 
public class ResourceController {
	@Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
private ResourceRepository resourceRepository;

@GetMapping(path="/add") // Map ONLY GET Requests
public @ResponseBody String addNewResource (@RequestParam String status
	, @RequestParam String date) {
// @ResponseBody means the returned String is the response, not a view name
// @RequestParam means it is a parameter from the GET or POST request

Resource n = new Resource();
n.setstatus(status);
n.setdate(date);
resourceRepository.save(n);
return "Saved";
}

@GetMapping(path="/all")
public @ResponseBody Iterable<Resource> getAllUsers() {
// This returns a JSON or XML with the users
return resourceRepository.findAll();
}
}
